spring.application.name=auth-service
server.port=8081

# H2 In-Memory Database (Chạy trên RAM)
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Chuỗi bí mật JWT
jwt.secret=CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te
jwt.expiration-ms=86400000
