spring.application.name=course-service
server.port=8081

# Tat tu dong ket noi database va JPA Hibernate khi chua co DB (Da comment de bat lai JPA)
#spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.jdbc.autoconfigure.DataSourceInitializationAutoConfiguration

# Thong tin ket noi H2 In-Memory Database (Chay khong can DB that)
spring.datasource.url=jdbc:h2:mem:coursedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hien thi console h2 tren trinh duyet o duong dan /h2-console
spring.h2.console.enabled=true

# Hibernate ddl-auto (tu dong tao bang)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
